export interface Quote {
  text: string;
  author: string;
}

// A large, deduplicated pool of sales/motivational quotes. One is shown per
// day on the Dashboard (see quoteOfTheDay), picked deterministically from
// the day of year so everyone on the team sees the same quote that day.
export const SALES_QUOTES: Quote[] = [
  { text: 'Make a customer, not a sale.', author: 'Katherine Barchetti' },
  { text: 'You have to drop your sales mentality and start working with your prospects as if they’ve already hired you.', author: 'Jill Konrath' },
  { text: 'Great salespeople are relationship builders who provide value and help their customers win.', author: 'Jeffrey Gitomer' },
  { text: 'Pretend that every single person you meet has a sign around his or her neck that says, ‘Make me feel important.’ Not only will you succeed in sales, you will succeed in life.', author: 'Mary Kay Ash' },
  { text: 'Customers don’t care at all whether you close the deal or not. They care about improving their business.', author: 'Aaron Ross' },
  { text: 'Most people think ‘selling’ is the same as ‘talking’. But the most effective salespeople know that listening is the most important part of their job.', author: 'Roy Bartell' },
  { text: 'If you are not taking care of your customer, your competitor will.', author: 'Bob Hooey' },
  { text: 'You can have everything in life you want if you will just help enough other people get what they want.', author: 'Zig Ziglar' },
  { text: 'The secret of getting ahead is getting started.', author: 'Mark Twain' },
  { text: 'The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.', author: 'Vince Lombardi' },
  { text: 'I am who I am today because of the choices I made yesterday.', author: 'Eleanor Roosevelt' },
  { text: 'Opportunities are usually disguised as hard work, so most people don’t recognize them.', author: 'Ann Landers' },
  { text: 'The first part of success is ‘Get-to-it-iveness’; the second part of success is ‘Stick-to-it-iveness’.', author: 'Orison Marden' },
  { text: 'On any given Monday I am one sale closer and one idea away from being a millionaire.', author: 'Larry D. Turner' },
  { text: 'The vision of a champion is bent over, drenched in sweat, at the point of exhaustion when nobody else is looking.', author: 'Mia Hamm' },
  { text: 'I’m not a product of my circumstances. I am a product of my decisions.', author: 'Stephen Covey' },
  { text: 'Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.', author: 'Thomas Edison' },
  { text: 'Sales success comes after you stretch yourself past your limits on a daily basis.', author: 'Omar Periu' },
  { text: 'You are what you repeatedly do. Excellence, then, is not an act, but a habit.', author: 'Aristotle' },
  { text: 'Winning isn’t everything, but wanting to win is.', author: 'Vince Lombardi' },
  { text: 'Ninety percent of selling is conviction and 10 percent is persuasion.', author: 'Shiv Khera' },
  { text: 'I like to think of sales as the ability to gracefully persuade, not manipulate, a person or persons into a win-win situation.', author: 'Bo Bennett' },
  { text: 'Don’t find customers for your products, find products for your customers.', author: 'Seth Godin' },
  { text: 'In sales, a referral is a key to the door of resistance.', author: 'Bo Bennett' },
  { text: 'Your most unhappy customers are your greatest source of learning.', author: 'Bill Gates' },
  { text: 'A-B-C. Always Be Closing.', author: 'Blake, Glengarry Glen Ross' },
  { text: 'You’re only as good as your last sale, so you put your all into something and just hope that from that you can get your next job.', author: 'Josh Peck' },
  { text: 'Turn up the volume of your computer speakers before making calls. You may hear money talk.', author: 'Pipedrive' },
  { text: 'Do not let what you cannot do interfere with what you can do.', author: 'John R. Wooden' },
  { text: 'Some men see things as they are and ask why … I dream of things that never were and ask why not?', author: 'Robert Kennedy' },
  { text: 'The same wind blows on us all. What matters is not the blowing of the wind but the set of the sail.', author: 'Jim Rohn' },
  { text: 'The most unprofitable item ever manufactured is an excuse.', author: 'John Mason' },
  { text: 'What we dwell on is who we become.', author: 'Oprah Winfrey' },
  { text: 'Every email is an opportunity to test a different benefit or angle.', author: 'Heather R Morgan' },
  { text: 'There is no easy button in sales. Prospecting is hard, emotionally draining work, and it is the price you have to pay to earn a high income.', author: 'Jeb Blount' },
  { text: 'Train your prospects to pay attention and to open and read emails that you send. Don’t encourage them to ignore or delete your messages because they are of inconsistent or no value to them.', author: 'Bridget Gleason' },
  { text: 'High-level buyers want to talk to people who know more than they do. They hunger not for information but insight.', author: 'Barbara Weaver Smith' },
  { text: 'Prospects are making their purchase decision based on whether they think you understand their problems and you have the knowledge, resources, and commitment to solving them.', author: 'Trish Bertuzzi' },
  { text: 'The key is not to call the decision-maker. The key is to have the decision maker call you.', author: 'Jeffrey Gitomer' },
  { text: 'It’s not about having the right opportunities. It’s about handling the opportunities right.', author: 'Mark Hunter' },
  { text: 'Remember, people don’t believe it when WE say it, they believe it when THEY say it.', author: 'Shari Levitin' },
  { text: 'Buyers do business with you, not with your company and not with your technology.', author: 'Joanne Black' },
  { text: 'You can’t propose a mutually beneficial business relationship if you can’t understand their business.', author: 'Craig Rosenberg' },
  { text: 'You will attract way more buyers if you are offering to teach them something of value to them than you will ever attract by simply trying to sell them your product or service.', author: 'Chet Holmes' },
  { text: 'Sales success comes from the right balance of quality human interaction and appropriate use of supplemental tools.', author: 'Deb Calvert' },
  { text: 'The sales compensation plan is Batman, the sales contest is Robin.', author: 'Mark Roberge' },
  { text: 'Statistics suggest that when customers complain, business owners and managers ought to get excited about it. The complaining customer represents a huge opportunity for more business.', author: 'Zig Ziglar' },
  { text: 'Killer salespeople uncover true problems behind desired solutions.', author: 'Aaron Ross' },
  { text: 'If you harness the power of innovation, you’ll convert sales complexity into a brutal competitive advantage.', author: 'Tim Sanders' },
  { text: 'Success is the sum of small efforts, repeated day in and day out.', author: 'Robert Collier' },
  { text: 'Filter everything you’re doing, saying and pitching and you’ll improve just about every metric you care about today.', author: 'Matt Heinz' },
  { text: 'Leaders must get across the why as well as the what.', author: 'John Doerr' },
  { text: 'If you really look closely, most overnight successes took a long time.', author: 'Steve Jobs' },
  { text: 'Success is where preparation and opportunity meet.', author: 'Bobby Unser' },
  { text: 'If you want to succeed you should strike out on new paths, rather than travel the worn paths of accepted success.', author: 'John D Rockefeller' },
  { text: 'Success is a science; if you have the conditions, you get the result.', author: 'Oscar Wilde' },
  { text: 'Become the person who would attract the results you seek.', author: 'Jim Cathcart' },
  { text: 'It is not your customer’s job to remember you. It is your obligation and responsibility to make sure they don’t have the chance to forget you.', author: 'Patricia Fripp' },
  { text: 'All things being equal, people will do business with, and refer business to, those people they know, like, and trust.', author: 'Bob Burg' },
  { text: 'Sales are contingent upon the attitude of the salesman, not the attitude of the prospect.', author: 'William Clement Stone' },
  { text: 'All progress takes place outside the comfort zone.', author: 'Michael John Bobak' },
  { text: 'Quality performance starts with a positive attitude.', author: 'Jeffrey Gitomer' },
  { text: 'The best salespeople know that their expertise can become their enemy in selling. At the moment they are tempted to tell the buyer what ‘he needs to do,’ they instead offer a story about a peer of the buyer.', author: 'Mike Bosworth' },
  { text: 'The one thing you’re putting off or dreading? That’s your brain telling you it’s the thing you need to do most and next. Get it done. Stop dreading. Do.', author: 'Nancy Nardin' },
  { text: 'An effective process has the reps thinking in terms of ‘them’ as opposed to ‘us.’', author: 'Trish Bertuzzi' },
  { text: 'If you’re not making mistakes, then you’re not doing anything.', author: 'John Wooden' },
  { text: 'Leadership is a choice, not a position.', author: 'Stephen Covey' },
  { text: 'Opportunities don’t happen. You create them.', author: 'Chris Grosser' },
  { text: 'Accountability breeds responsibility.', author: 'Stephen Covey' },
  { text: 'Leaders must be close enough to relate to others, but far enough ahead to motivate them.', author: 'John C. Maxwell' },
  { text: 'Be an example. Are you prompt? Are you professional? Are you engaged? As sales leaders, we have to set the bar high for ourselves as well as our teams.', author: 'Lori Richardson' },
  { text: 'Sometimes the most influential thing we can do is listen.', author: 'Bob Burg' },
  { text: 'Stop saying ‘later.’ You WON’T do it later. Do it or decide not to do it.', author: 'Chris Brogan' },
  { text: 'Treat your salesperson like you would treat your most important customer — because he is!', author: 'Colleen Stanley' },
  { text: 'A salesperson’s ethics and values contribute more to sales success than do techniques or strategies.', author: 'Ron Willingham' },
  { text: 'For a leader, getting results is more important than getting credit.', author: 'Bob Burg' },
  { text: 'Success depends upon previous preparation, and without such preparation, there is sure to be failure.', author: 'Confucius' },
  { text: 'Successful people do what unsuccessful people are not willing to do. Don’t wish it were easier; wish you were better.', author: 'Jim Rohn' },
  { text: 'When a team takes ownership of its problem, the problem gets solved.', author: 'Jocko Willink' },
  { text: 'What you focus on is what you get.', author: 'Bob Burg' },
  { text: 'I never see failure as failure, but only as the game I must play and win.', author: 'Tom Hopkins' },
  { text: 'Expect to make some mistakes when you try new and different approaches.', author: 'Harvey Mackay' },
  { text: 'Begin by always expecting good things to happen.', author: 'Tom Hopkins' },
  { text: 'Learn from the mistakes of others. You can’t live long enough to make them yourself.', author: 'Eleanor Roosevelt' },
  { text: 'Beware of monotony; it’s the mother of all deadly sins.', author: 'Edith Wharton' },
  { text: 'Don’t watch the clock; do what it does. Keep going.', author: 'Sam Levenson' },
  { text: 'What differentiates sellers today is their ability to bring fresh ideas.', author: 'Jill Konrath' },
  { text: 'The way to get started is to quit talking and begin doing.', author: 'Walt Disney' },
  { text: 'Either run the day or the day runs you.', author: 'Jim Rohn' },
  { text: 'Don’t sell life insurance. Sell what life insurance can do.', author: 'Ben Feldman' },
  { text: 'A mediocre idea that generates enthusiasm will go further than a great idea that inspires no one.', author: 'Mary Kay Ash' },
  { text: 'A rock pile ceases to be a rock pile the moment a single man contemplates it, bearing within him the image of a cathedral.', author: 'Antoine de Saint-Exupery' },
  { text: 'Everything you’ve ever wanted is on the other side of fear.', author: 'George Addair' },
  { text: 'Human beings have an innate inner drive to be autonomous, self-determined, and connected to one another. And when that drive is liberated, people achieve more and live richer lives.', author: 'Daniel Pink' },
  { text: 'I attribute my success to this: I never gave or took any excuse.', author: 'Florence Nightingale' },
  { text: 'You miss 100% of the shots you don’t take.', author: 'Wayne Gretzky' },
  { text: 'A goal is a dream with a deadline.', author: 'Napoleon Hill' },
  { text: 'Big shots are only little shots who keep shooting.', author: 'Christopher Morley' },
  { text: 'If you aren’t going all the way, why go at all?', author: 'Joe Namath' },
  { text: 'Act as if what you do makes a difference. It does.', author: 'William James' },
  { text: 'You just can’t beat the person who never gives up.', author: 'Babe Ruth' },
  { text: 'Outstanding people have one thing in common: an absolute sense of mission.', author: 'Zig Ziglar' },
  { text: 'Do you want to know who you are? Don’t ask. Act! Action will delineate and define you.', author: 'Thomas Jefferson' },
  { text: 'In the middle of every difficulty lies opportunity.', author: 'Albert Einstein' },
  { text: 'It ain’t over ’til it’s over.', author: 'Yogi Berra' },
  { text: 'Keep yourself positive, cheerful and goal-oriented. Sales success is 80% attitude and only 20% aptitude.', author: 'Brian Tracy' },
  { text: 'Knowing is not enough; we must apply. Wishing is not enough; we must do.', author: 'Johann Wolfgang Von Goethe' },
  { text: 'Lean in, speak out, have a voice in your organization, and never use the word ‘sorry.’', author: 'Trish Bertuzzi' },
  { text: 'Motivation is what gets you started. Habit is what keeps you going.', author: 'Jim Rohn' },
  { text: 'Motivation will almost always beat mere talent.', author: 'Norman Ralph Augustine' },
  { text: 'Nothing is particularly hard if you divide it into small jobs.', author: 'Henry Ford' },
  { text: 'Often when you think you’re at the end of something, you’re at the beginning of something else.', author: 'Fred Rogers' },
  { text: 'Setting goals is the first step in turning the invisible into the visible.', author: 'Tony Robbins' },
  { text: 'Success is the ability to go from failure to failure without losing your enthusiasm.', author: 'Zig Ziglar' },
  { text: 'Success is often achieved by those who don’t know that failure is inevitable.', author: 'Coco Chanel' },
  { text: 'Success seems to be connected with action. Successful people keep moving. They make mistakes but they don’t quit.', author: 'Conrad Hilton' },
  { text: 'The harder the conflict, the more glorious the triumph.', author: 'Thomas Paine' },
  { text: 'The most difficult thing is the decision to act, the rest is merely tenacity. The fears are paper tigers. You can do anything you decide to do.', author: 'Amelia Earhart' },
  { text: 'The only question is whether you’re going to do it today or tomorrow. If you keep saying you’re going to do it tomorrow, you’ll never do it. You have to get on it today.', author: 'Warren Buffett' },
  { text: 'There is always room at the top.', author: 'Daniel Webster' },
  { text: 'To build a long-term, successful enterprise, when you don’t close a sale, open a relationship.', author: 'Patricia Fripp' },
  { text: 'Value the relationship more than the quota.', author: 'Jeff Gitomer' },
  { text: 'We cannot solve our problems with the same thinking we used when we created them.', author: 'Albert Einstein' },
  { text: 'We herd sheep, we drive cattle, we lead people. Lead me, follow me, or get out of my way.', author: 'George S. Patton' },
  { text: 'Well done is better than well said.', author: 'Benjamin Franklin' },
  { text: 'Whatever you are, be a good one.', author: 'Abraham Lincoln' },
  { text: 'Whether you think you can or you think you can’t, you’re right.', author: 'Henry Ford' },
  { text: 'You must expect great things of yourself before you can do them.', author: 'Michael Jordan' },
  { text: 'Every morning in Africa, a gazelle wakes up. It knows it must outrun the fastest lion or it will be killed... when the sun comes up, you’d better be running.', author: 'Christopher McDougall' },
  { text: 'Even if you are on the right track, you’ll get run over if you just sit there.', author: 'Will Rogers' },
  { text: 'Trouble is the only opportunity in work clothes.', author: 'Henry J. Kaiser' },
  { text: '80% of success is showing up.', author: 'Woody Allen' },
  { text: 'Don’t wish it were easier, wish you were better.', author: 'Jim Rohn' },
  { text: 'Life shrinks or expands in proportion to one’s courage.', author: 'Anais Nin' },
  { text: 'Whatever the mind of man can conceive and believe, it can achieve.', author: 'Napoleon Hill' },
  { text: 'A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.', author: 'Winston Churchill' },
  { text: 'Focus on being productive instead of being busy.', author: 'Tim Ferriss' },
  { text: 'We’re not here to take part, we’re here to take over.', author: 'Conor McGregor' },
  { text: 'By working faithfully eight hours a day, you may eventually get to be boss and work twelve hours a day.', author: 'Robert Frost' },
  { text: 'Time is the friend of the wonderful business, the enemy of the mediocre.', author: 'Warren Buffett' },
  { text: 'Timing, perseverance, and ten years of trying will eventually make you look like an overnight success.', author: 'Biz Stone' },
  { text: 'Goals allow you to control the direction of change in your favour.', author: 'Brian Tracy' },
  { text: 'If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on.', author: 'Sheryl Sandberg' },
  { text: 'The expert in anything was once a beginner.', author: 'Helen Hayes' },
  { text: 'Be so good, they can’t ignore you.', author: 'Steve Martin' },
  { text: 'Success is walking from failure to failure with no loss of enthusiasm.', author: 'Winston Churchill' },
  { text: 'A successful man is one who can lay a firm foundation with the bricks that others throw at him.', author: 'David Brinkley' },
  { text: 'The only limit to our realization of tomorrow will be our doubts of today.', author: 'Franklin D. Roosevelt' },
  { text: 'Trying is winning in the moment.', author: 'Dan Waldschmidt' },
  { text: 'The key to mastering any kind of sales is switching statements about you — how great you are, and what you do — to statements about them.', author: 'Jeffrey Gitomer' },
  { text: 'There are no shortcuts to any place worth going.', author: 'Beverly Sills' },
  { text: 'Before LinkedIn and other social networks, in the sales world, ABC stood for Always Be Closing. Now it means Always Be Connecting.', author: 'Jill Rowley' },
  { text: 'Treat objections as requests for further information.', author: 'Brian Tracy' },
  { text: 'You don’t close a sale; you open a relationship if you want to build a long-term, successful enterprise.', author: 'Patricia Fripp' },
  { text: 'Companies should be selling ideas more than benefits. Sell ideas, not stuff.', author: 'Aaron Ross' },
  { text: 'The questions you ask are more important than the things you could ever say.', author: 'Thomas Freese' },
  { text: 'Far too often, salespeople get ahead of the prospect. They predict a close date based on their quota instead of on the prospect’s needs. The only way to know when a deal will close is to ask the customer.', author: 'Alice Heiman' },
  { text: 'Sellers who listen to buyers carefully and then give them the missing ingredients — those are the ones who stand out.', author: 'Deb Calvert' },
  { text: 'Selling is really about having conversations with people and helping improve their company or their life.', author: 'Lori Richardson' },
  { text: 'Selling is essentially a transference of feelings.', author: 'Zig Ziglar' },
  { text: 'It’s no longer about interrupting, pitching and closing. It is about listening, diagnosing and prescribing.', author: 'Mark Roberge' },
  { text: 'Selling through social channels is the closest thing to being a fly on the wall in your customers, prospects and competitors’ world.', author: 'Jim Keenan' },
  { text: 'In high-productivity sales organizations, salespeople do not cause customer acquisition growth, they fulfill it.', author: 'Aaron Ross' },
  { text: 'Successful people ask a lot more questions during sales calls than do their less successful colleagues.', author: 'Neil Rackham' },
  { text: 'I have never worked a day in my life without selling. If I believe in something, I sell it, and I sell it hard.', author: 'Estée Lauder' },
  { text: 'There is no magic to closing. There are no magic phrases. Closing the deal is completely dependent on the situation.', author: 'Alice Heiman' },
  { text: 'Sales is an outcome, not a goal. It’s a function of doing numerous things right, starting from the moment you target a potential prospect until you finalize the deal.', author: 'Jill Konrath' },
  { text: 'The real problem with closing is not adequately defining or diagnosing the prospect’s problems in the first place.', author: 'Keith Eades' },
  { text: 'The customer doesn’t care about features — they care about solving their problems.', author: 'Trish Bertuzzi' },
  { text: 'A straightforward way to show buyers that you genuinely like them is to identify something about them that you sincerely appreciate.', author: 'David Hoffeld' },
  { text: 'The story is the heart of the sale.', author: 'Matthew Pollard' },
  { text: 'If you don’t believe in what you’re selling, neither will your prospect.', author: 'Frank Bettger' },
  { text: 'Buyers don’t believe anything you have to say to them about your product or service until they first believe in you.', author: 'Deb Calvert' },
  { text: 'Humanize the sales process or perish.', author: 'Steli Efti' },
  { text: 'Your competition is everything else your prospect could conceivably spend their money on.', author: 'Don Cooper' },
  { text: 'The competitor to be feared is one who never bothers about you at all, but goes on making his own business better all the time.', author: 'Henry Ford' },
  { text: 'Prospecting — find the man with the problem.', author: 'Ben Friedman' },
  { text: 'Every sale has five obstacles: no need, no money, no hurry, no desire, no trust.', author: 'Zig Ziglar' },
  { text: 'Every strike brings me closer to the next home run.', author: 'Babe Ruth' },
  { text: 'The best revenge is massive success.', author: 'Frank Sinatra' },
  { text: 'You don’t learn to walk by following rules. You learn by doing and falling over.', author: 'Richard Branson' },
  { text: 'Nobody likes to be sold to, but everybody likes to buy.', author: 'Earl Taylor' },
  { text: 'Whenever an individual or a business decides that success has been attained, progress stops.', author: 'Thomas J. Watson Jr' },
  { text: 'There will be obstacles. There will be doubters. There will be mistakes. But with hard work, there are no limits.', author: 'Michael Phelps' },
  { text: 'If you can’t describe what you are doing as a process, you don’t know what you’re doing.', author: 'Edward Deming' },
  { text: 'If you do not have a defined process that moves your people forward so they can achieve greater results, then what is it you are managing?', author: 'Keith Rosen' },
  { text: 'Success is the culmination of failures, mistakes, false starts, confusion, and the determination to keep going anyway.', author: 'Nick Gleason' },
  { text: 'Business opportunities are like buses, there’s always another one coming.', author: 'Richard Branson' },
  { text: 'Success is never final. Failure is never fatal. It is courage that counts.', author: 'Winston Churchill' },
  { text: 'If you don’t give up on something you truly believe in, you will find a way.', author: 'Roy T. Bennett' },
  { text: 'Leadership belongs to those who take it.', author: 'Sheryl Sandberg' },
  { text: 'Great things are done by a series of small things done together.', author: 'Vincent van Gogh' },
  { text: 'Failure will never overtake me if my determination to succeed is strong enough.', author: 'Og Mandino' },
  { text: 'We generate fears while we sit. We overcome them by action.', author: 'Dr. Henry Link' },
  { text: 'One of the best predictors of ultimate success isn’t natural talent or even industry expertise, but how you explain your failures and rejections.', author: 'Daniel H. Pink' },
  { text: 'Courage is not having the strength to go on; it is going on when you don’t have the strength.', author: 'Teddy Roosevelt' },
  { text: 'Fall seven times, stand up eight.', author: 'Japanese Proverb' },
  { text: 'So long as new ideas are created, sales will continue to reach new highs.', author: 'Dorothea Brande' },
  { text: 'No matter how deep a study you make, what you really have to rely on is your own intuition, and when it comes down to it, you really don’t know what’s going to happen until you do it.', author: 'Konosuke Matsushita' },
  { text: 'When reps take the role of a curious student rather than an informed expert, buyers are much more inclined to engage.', author: 'Jeff Hoffman' },
  { text: 'Wanting something is not enough. You must hunger for it. Your motivation must be absolutely compelling in order to overcome the obstacles that will invariably come your way.', author: 'Les Brown' },
  { text: 'Today is always the most productive day of your week.', author: 'Mark Hunter' },
  { text: 'Never put off till tomorrow what you can do today.', author: 'Thomas Jefferson' },
  { text: 'Hard work is about risk. It begins when you deal with the things that you’d rather not deal with: fear of failure, fear of standing out, fear of rejection.', author: 'Seth Godin' },
  { text: 'Never confuse activity with accomplishment.', author: 'Lori Richardson' },
  { text: 'Talking isn’t selling and selling isn’t closing.', author: 'Steli Efti' },
  { text: 'For every sale you miss because you were too enthusiastic, you’ll miss a hundred because you weren’t enthusiastic enough.', author: 'Zig Ziglar' },
  { text: 'Don’t expect to be motivated every day to get out there and make things happen. You won’t be. Don’t count on motivation. Count on discipline.', author: 'Jocko Willink' },
  { text: 'Grit, in a word, is stamina. But it’s not just stamina in your effort. It’s also stamina in your direction, stamina in your interests.', author: 'Angela Duckworth' },
  { text: 'Change before you have to.', author: 'Jack Welch' },
  { text: 'Be miserable. Or motivate yourself. Whatever has to be done, it’s always your choice.', author: 'Wayne Dyer' },
  { text: 'Learn the rules like a pro, so you can break them like an artist.', author: 'Pablo Picasso' },
  { text: 'If you were happy every day of your life, you wouldn’t be human, you’d be a game show host.', author: 'Gabriel Heather' },
  { text: 'A good listener is not only popular everywhere, but after a while he knows something.', author: 'Wilson Mizner' },
  { text: 'You will never find time for anything. If you want time you must make it.', author: 'Charles Robert Buxton' },
  { text: 'You have to learn the rules of the game. And then you have to play better than anyone else.', author: 'Albert Einstein' },
  { text: 'Think twice before you speak, because your words and influence will plant the seed of either success or failure in the mind of another.', author: 'Napoleon Hill' },
  { text: 'The road to Easy Street goes through the sewer.', author: 'John Madden' },
  { text: 'If you’re going through hell, keep going.', author: 'Winston Churchill' },
  { text: 'What you lack in talent can be made up with desire, hustle, and giving 110% all the time.', author: 'Don Zimmer' },
  { text: 'Don’t worry about failures, worry about the chances you miss when you don’t even try.', author: 'Jack Canfield' },
  { text: 'Always do your best. What you plant now, will harvest later.', author: 'Og Mandino' },
  { text: 'If football taught me anything about business, it is that you win the game one play at a time.', author: 'Fran Tarkenton' },
  { text: 'The man who will use his skill and constructive imagination to see how much he can give for a dollar, instead of how little he can give for a dollar, is bound to succeed.', author: 'Henry Ford' },
  { text: 'It is the cold that is dead — not the calling. No one should be cold calling anymore, meaning having a name and number, but lacking a compelling reason to call.', author: 'Trish Bertuzzi' },
  { text: 'Numbers alone won’t fix anything. But they will help you identify where the problem is.', author: 'Steli Efti' },
  { text: 'Approach each customer with the idea of helping him or her solve a problem or achieve a goal, not of selling a product or service.', author: 'Brian Tracy' },
  { text: 'If we had no winter, the spring would not be so pleasant; if we did not sometimes taste of adversity, prosperity would not be so welcome.', author: 'Josh Billings' },
  { text: 'The most common way people give up their power is by thinking they don’t have any.', author: 'Alice Walker' },
  { text: 'You need to be able to paint a picture in a conversation. The lost part of sales is the storytelling side.', author: 'Richard Harris' },
  { text: 'Practice is just as valuable as a sale. The sale will make you a living; the skill will make you a fortune.', author: 'Jim Rohn' },
  { text: 'Two roads diverged in a wood, and I — I took the one less traveled by, and that has made all the difference.', author: 'Robert Frost' },
  { text: 'You are never too old to set another goal or to dream a new dream.', author: 'C.S. Lewis' },
  { text: 'Don’t celebrate closing a sale, celebrate opening a relationship.', author: 'Patricia Fripp' },
  { text: 'How you sell matters. What your process is matters. But how your customers feel when they engage with you matters more.', author: 'Tiffani Bova' },
  { text: 'If your sales have tanked, maybe the issue is not your lack of sales skills, but that you are rushing the knowing and trusting aspects of the buying process.', author: 'Leanne Hoagland-Smith' },
  { text: 'Sales is not about selling anymore, but about building trust and educating.', author: 'Siva Devaki' },
  { text: 'The best salespeople wonder what it would be like to be in the other person’s shoes.', author: 'Bob Phibbs' },
  { text: 'To me, job titles don’t matter. Everyone is in sales. It’s the only way we stay in business.', author: 'Harvey Mackay' },
  { text: 'Fortune favors the bold.', author: 'Virgil' },
  { text: 'High expectations are the key to everything.', author: 'Sam Walton' },
  { text: 'With every rejection, you are one step closer to success.', author: 'Calvin K. Lee' },
  { text: 'No one can make you feel inferior without your consent.', author: 'Eleanor Roosevelt' },
  { text: 'I love working with customers. Sales has really influenced everything I do. It has instilled in me the important traits of operating with a sense of urgency and listening to people.', author: 'Jeffrey R. Immelt' },
  { text: 'To succeed at selling a losing product, you must develop seriously superior sales techniques.', author: 'Ben Horowitz' },
  { text: 'Keep your sales pipeline full by prospecting continuously. Always have more people to see than you have time to see them.', author: 'Brian Tracy' },
  { text: 'Your life can only get better when you do. Do something every day to improve your key skill areas.', author: 'Brian Tracy' },
  { text: 'If you are not moving closer to what you want in sales — or in life — you probably aren’t doing enough asking.', author: 'Jack Canfield' },
  { text: 'Dream big! There are no limitations to how good you can become or how high you can rise except the limits you put on yourself.', author: 'Brian Tracy' },
  { text: 'There’s no lotion or potion that will make sales faster and easier for you — unless your potion is hard work.', author: 'Jeffrey Gitomer' },
  { text: 'You can’t learn anything if you are doing all the talking. Salespeople should always be developing their earQ, not their IQ.', author: 'Harvey Mackay' },
  { text: 'Poor firms ignore their competitors; average firms copy their competitors; winning firms lead their competitors.', author: 'Philip Kotler' },
  { text: 'People don’t ask for facts in making up their minds. They would rather have one good, soul-satisfying emotion than a dozen facts.', author: 'Robert Keith Leavitt' },
  { text: 'Sales is the most important aspect of a company, which in turn is about how well you treat your customer and stay ahead of your customer’s requirements.', author: 'Mark Cuban' },
  { text: 'People often say that motivation doesn’t last. Well, neither does bathing. That’s why we recommend it daily.', author: 'Zig Ziglar' },
  { text: 'Catch a man a fish, and you can sell it to him. Teach a man to fish, and you ruin a wonderful business opportunity.', author: 'Karl Marx' },
  { text: 'Nothing is impossible; the word itself says ‘I’m possible!’', author: 'Audrey Hepburn' },
  { text: 'Innovation distinguishes between a leader and a follower.', author: 'Steve Jobs' },
  { text: 'The successful warrior is the average man, with laser-like focus.', author: 'Bruce Lee' },
  { text: 'Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all.', author: 'Dale Carnegie' },
  { text: 'You don’t need a big close, as many sales reps believe. Keep the customer actively involved throughout the presentation, and watch your results improve.', author: 'Harvey MacKay' },
  { text: 'It is not necessary to do extraordinary things to get extraordinary results.', author: 'Warren Buffett' },
];

function dayOfYear(d: Date): number {
  const start = new Date(d.getFullYear(), 0, 0);
  const diff = d.getTime() - start.getTime();
  return Math.floor(diff / 86400000);
}

// Deterministic "quote of the day" — same for everyone, changes once every 24h.
export function quoteOfTheDay(date: Date = new Date()): Quote {
  const index = dayOfYear(date) % SALES_QUOTES.length;
  return SALES_QUOTES[index];
}
