"""Water bodies from the master plan: mask the lake blues, clean, trace each lake's outer
edge and simplify it. Writes src/lib/waterBodies.ts (polygons in % of the plan)."""
import os
from collections import deque, defaultdict
import numpy as np
from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
a = np.asarray(Image.open(os.path.join(REPO, 'public/master-plan/l1.webp')).convert('RGB')).astype(int)
H0, W0 = a.shape[:2]
r, g, b = a[..., 0], a[..., 1], a[..., 2]
# Lake blue-teal, plus the paler green-teal of the creek by holes 10-11; grass has a high red channel.
mask = ((b > r + 55) & (b >= g + 5) & (g > r + 40) & (b > 120)) | ((b > r + 50) & (np.abs(g - b) < 20) & (g > r + 60) & (b > 130))

S = 4
h, w = H0 // S, W0 // S
m = mask[:h * S, :w * S].reshape(h, S, w, S).mean((1, 3)) >= 0.5

lab = np.zeros((h, w), int)
n = 0
sizes = {}
for y in range(h):
    for x in range(w):
        if m[y, x] and not lab[y, x]:
            n += 1
            q = deque([(y, x)]); lab[y, x] = n; c = 0
            while q:
                cy, cx = q.popleft(); c += 1
                for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    ny, nx = cy + dy, cx + dx
                    if 0 <= ny < h and 0 <= nx < w and m[ny, nx] and not lab[ny, nx]:
                        lab[ny, nx] = n; q.append((ny, nx))
            sizes[n] = c
keep = [k for k, v in sizes.items() if v >= 40]


def loops(cells):
    """Boundary loops of a cell set, as vertex lists (grid corners)."""
    nxt = defaultdict(list)
    for (y, x) in cells:
        # directed edges, water on the right-hand side when walking
        if (y - 1, x) not in cells: nxt[(x, y)].append((x + 1, y))
        if (y, x + 1) not in cells: nxt[(x + 1, y)].append((x + 1, y + 1))
        if (y + 1, x) not in cells: nxt[(x + 1, y + 1)].append((x, y + 1))
        if (y, x - 1) not in cells: nxt[(x, y + 1)].append((x, y))
    out = []
    while nxt:
        start = next(iter(nxt))
        loop = [start]; cur = start
        while True:
            outs = nxt[cur]
            nx_ = outs.pop()
            if not outs: del nxt[cur]
            cur = nx_
            if cur == start: break
            loop.append(cur)
            if cur not in nxt: break
        out.append(loop)
    return out


def area(loop):
    return 0.5 * sum(loop[i][0] * loop[(i + 1) % len(loop)][1] - loop[(i + 1) % len(loop)][0] * loop[i][1] for i in range(len(loop)))


def rdp(pts, eps):
    if len(pts) < 3: return pts
    (x1, y1), (x2, y2) = pts[0], pts[-1]
    dx, dy = x2 - x1, y2 - y1
    L = (dx * dx + dy * dy) ** 0.5 or 1e-9
    dmax, idx = 0, 0
    for i in range(1, len(pts) - 1):
        d = abs(dy * pts[i][0] - dx * pts[i][1] + x2 * y1 - y2 * x1) / L
        if d > dmax: dmax, idx = d, i
    if dmax > eps:
        return rdp(pts[:idx + 1], eps)[:-1] + rdp(pts[idx:], eps)
    return [pts[0], pts[-1]]


polys = []
for k in keep:
    ys, xs = np.nonzero(lab == k)
    cells = set(zip(ys.tolist(), xs.tolist()))
    best = max(loops(cells), key=lambda L: abs(area(L)))
    if len(best) > 3:
        # a closed loop collapses under RDP, so split it at the point farthest from its start
        far = max(range(len(best)), key=lambda i: (best[i][0] - best[0][0]) ** 2 + (best[i][1] - best[0][1]) ** 2)
        simp = rdp(best[:far + 1], 1.2)[:-1] + rdp(best[far:] + [best[0]], 1.2)[:-1]
        polys.append([[round(x / w * 100, 2), round(y / h * 100, 2)] for x, y in simp])

polys.sort(key=lambda p: -len(p))
lines = ['// Generated by scripts/extract_water.py from the master plan - do not edit by hand.',
         '// Lakes and ponds as polygons, in % of the plan (x from left, y from top).',
         'export const WATER_BODIES: [number, number][][] = [']
for p in polys:
    lines.append('  [' + ', '.join(f'[{x}, {y}]' for x, y in p) + '],')
lines.append('];')
open(os.path.join(REPO, 'src/lib/waterBodies.ts'), 'w', newline='\n').write('\n'.join(lines) + '\n')
print(len(polys), 'water bodies;', sum(len(p) for p in polys), 'points')
